name: Compile and Release foxglow.json

on:
  push:
    branches:
      - main
    paths:
      - foxglow.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up sing-box
      run: bash <(curl -fsSL https://sing-box.app/deb-install.sh)

    - name: Compile foxglow.json to binary format
      run: sing-box rule-set compile foxglow.json

    - name: Create a release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: "release-${{ github.event.head_commit.timestamp }}"
        release_name: ${{ github.event.head_commit.timestamp }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Move the latest tag
      run: |
        git fetch --tags
        git tag -f latest ${{ github.sha }}
        git push origin -f latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload foxglow.json
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./foxglow.json
        asset_name: foxglow.json
        asset_content_type: application/json

    - name: Upload foxglow.srs
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./foxglow.srs
        asset_name: foxglow.srs
        asset_content_type: application/octet-stream
